server:
  port: 9000
  servlet:
    session:
      cookie:
        name: MCP_AUTHSERVER_SESSION

spring:
  application:
    name: oauth2-authorization-server
  security:
    user:
      name: user
      password: password
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "mcp-client"
              client-secret: "{noop}mcp-secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "client_credentials"
                - "refresh_token"
              redirect-uris:
                - "http://127.0.0.1:8080/authorize/oauth2/code/authserver"
                - "http://localhost:8080/authorize/oauth2/code/authserver"
              scopes:
                - "openid"
                - "profile"
                - "mcp.read"
                - "mcp.write"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG